<?php
/**
 * Main config file.
 *
 * DO NOT EDIT THIS FILE.
 *
 * All configuration should be done either in your project's composer.json or `config/`
 * directory.
 *
 * phpcs:disable PSR1.Files.SideEffects
 */

// Load an escape hatch early load file, if it exists.
if ( file_exists( __DIR__ . '/.config/load-early.php' ) ) {
	require_once __DIR__ . '/.config/load-early.php';
}

// Load an escape hatch early load file, if it exists.
if ( file_exists( __DIR__ . '/.config/load.php' ) ) {
	require_once __DIR__ . '/.config/load.php';
}

// Load the plugin API (like add_action etc) early, so everything loaded
// via the Composer autoloaders can using actions.
require_once __DIR__ . '/wordpress/wp-includes/plugin.php';

// Load the whole autoloader very early, this will also include
// all `autoload.files` from all modules.
require_once __DIR__ . '/vendor/autoload.php';

// Load local-config file, if it exists.
if ( file_exists( __DIR__ . '/.config/local-config.php' ) ) {
	require_once __DIR__ . '/.config/local-config.php';
}

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/wordpress/' );
}

if ( ! defined( 'WP_CONTENT_DIR' ) ) {
	define( 'WP_CONTENT_DIR', __DIR__ . '/content' );
}

if ( ! defined( 'WP_CONTENT_URL' ) ) {
	$protocol = ! empty( $_SERVER['HTTPS'] ) ? 'https' : 'http';
	define( 'WP_CONTENT_URL', $protocol . '://' . $_SERVER['HTTP_HOST'] . '/content' );
}

if ( ! defined( 'WP_INITIAL_INSTALL' ) || ! WP_INITIAL_INSTALL ) {
	if ( ! defined( 'MULTISITE' ) ) {
		define( 'MULTISITE', true );
	}
}

if ( ! isset( $table_prefix ) ) {
	$table_prefix = getenv( 'TABLE_PREFIX' ) ?: 'wp_';
}

/*
 * DB constants are expected to be provided by other modules, as they are
 * environment specific.
 */
$required_constants = [
	'DB_HOST',
	'DB_NAME',
	'DB_USER',
	'DB_PASSWORD',
	'AUTH_KEY',
	'SECURE_AUTH_KEY',
	'LOGGED_IN_KEY',
	'NONCE_KEY',
	'AUTH_SALT',
	'SECURE_AUTH_SALT',
	'LOGGED_IN_SALT',
	'NONCE_SALT',
];

foreach ( $required_constants as $constant ) {
	if ( ! defined( $constant ) ) {
		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		die( "$constant constant is not defined." );
	}
}

if ( ! getenv( 'WP_PHPUNIT__TESTS_CONFIG' ) ) {
	require_once ABSPATH . 'wp-settings.php';
}
