name: Static Analysis (PHP/CSS/JS Linting)

on:
    pull_request:
        branches:
            - main
            - staging
            - development

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    linting:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    extensions: pcov

            -   name: Cache Composer dependencies
                uses: actions/cache@v2
                with:
                    path: /tmp/cache
                    key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}-${{ hashFiles('**/package-lock.json') }}

            -   name: Use Node.js 14
                uses: actions/setup-node@v2
                with:
                    node-version: 14.x

            -   name: Install dependencies
                uses: ramsey/composer-install@v1

            -   name: Install Node Dependencies
                run: npm install

            -   name: Run PHPCS
                run: ls -al && phpcs -i && composer lint

            -   name: Run ESLint
                run: npm run lint:js

            -   name: Run Stylint
                run: npm run lint:css
